
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Etec-User
 */
public class FrameCalc extends javax.swing.JFrame {

    /**
     * Creates new form FrameCalc
     */
    public FrameCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtValorHora = new javax.swing.JTextField();
        txtHorasTrab = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbDepNao = new javax.swing.JRadioButton();
        rbDepSim = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cmbDep = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cbxVT = new javax.swing.JCheckBox();
        cbxVA = new javax.swing.JCheckBox();
        cbxVR = new javax.swing.JCheckBox();
        cbxConv = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        lblResp = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(255, 204, 204));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        txtValorHora.setBackground(new java.awt.Color(255, 204, 204));
        txtValorHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorHoraActionPerformed(evt);
            }
        });

        txtHorasTrab.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("VALOR HORA TRABALHADA");

        jLabel2.setText("QUANTIDADES HORAS TRABALHADAS");

        buttonGroup1.add(rbDepNao);
        rbDepNao.setSelected(true);
        rbDepNao.setText("NÃO");
        rbDepNao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbDepNaoStateChanged(evt);
            }
        });

        buttonGroup1.add(rbDepSim);
        rbDepSim.setText("SIM");

        jLabel3.setText("POSSUI DEPENDENTES ?");

        cmbDep.setBackground(new java.awt.Color(255, 204, 204));
        cmbDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4 OU MAIS\t" }));
        cmbDep.setEnabled(false);

        jLabel5.setText("QUANTIDADE DE PARENTES");

        cbxVT.setText("VALE TRANSPORTE");
        cbxVT.setToolTipText("VT");

        cbxVA.setText("VALE ALIMENTAÇÃO");
        cbxVA.setToolTipText("VA");

        cbxVR.setText("VALE REFEIÇÃO");
        cbxVR.setToolTipText("VR");

        cbxConv.setText("CONVÊNIO");
        cbxConv.setToolTipText("CONV");

        jLabel4.setText("BENEFÍCIOS");

        btnLimpar.setBackground(new java.awt.Color(153, 153, 255));
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(153, 153, 255));
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblResp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResp.setText("AGUARDANDO CÁLCULO...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResp, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbDepNao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbDepSim))
                                    .addComponent(jLabel4)
                                    .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtHorasTrab)
                                    .addComponent(cmbDep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxVT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxVA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxVR)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxConv))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHorasTrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDepNao)
                    .addComponent(rbDepSim)
                    .addComponent(cmbDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxVT)
                    .addComponent(cbxVA)
                    .addComponent(cbxVR)
                    .addComponent(cbxConv))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(lblResp, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        //limpar TextFields
        txtHorasTrab.setText("");
        txtValorHora.setText("");
        //Marcar RdioButton
        rbDepNao.setSelected(true);
        //Desmarcar RadioButoon
        rbDepSim.setSelected(false);
        //Selecionar cmbDep.setSelectedIndex(0);
        cmbDep.setEnabled(false);
        cbxVT.setSelected(false);
         cbxVA.setSelected(false);
         cbxVR.setSelected(false);
          cbxConv.setSelected(false);
          lblResp.setText("A calcular");
       
    }//GEN-LAST:event_btnLimparActionPerformed

    private void rbDepNaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbDepNaoStateChanged
      //habilita e desabilita combo box
      if (rbDepNao.isSelected()== true) {
          cmbDep.setSelectedIndex(0);
          cmbDep.setEnabled(false); 
      } else {
            cmbDep.setEnabled(true); 
      }
    }//GEN-LAST:event_rbDepNaoStateChanged

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
      
       //CHAMAR MÉTODO,EXECUÇÃOO 
      if ( verificarVazio()== false){
      return;
      
      }
       
      if ( verificarNumeros()== false){
      return;
     }  
      
      double valorHora,qtdHora;
      
      valorHora = Double.parseDouble(txtValorHora.getText());
       qtdHora = Double.parseDouble(txtHorasTrab.getText());
      
       //OBJETO SENDO INSTANCIADO
     CalcSalarial calcSalarial = new CalcSalarial(valorHora,qtdHora);
     
     //OPÇÃO DE DEPENDENTES ATIVA OU NÃO
     if(rbDepSim.isSelected()){
         //
         int depSelec = cmbDep.getSelectedIndex();
         
        switch (depSelec){
            case 0:
                 depSelec = 1;
                break;
            case 1:
                depSelec = 2;
                break;
            case 2:
                depSelec = 3;
                break;
            case 3:
                depSelec = 4;
                break;
                
                 
        }
      //OBJETO(calcSalarial) + MÉTODO(AcrescentarDependentes) + VARIÁVEL QUE GUARDA VALOR DA CONVERSAO DO COMBO-BOX(depSelec) !!
      calcSalarial.AcrescentarDependentes(depSelec);
     } 
     if (cbxVA.isSelected()){
         calcSalarial.acrescentarVA();
     
     }
     if (cbxVT.isSelected()){
         calcSalarial.descontarVT();
     
     }
      if (cbxVR.isSelected()){
         calcSalarial.descontarVR();
     
     }
      if (cbxConv.isSelected()){
         calcSalarial.descontarCONV();
     
     }
     
     
     lblResp.setText ("<html>" +
                     "Salário Base: " + calcSalarial.getSalarioBase() +
                     "<br>Salário Líquido: " + calcSalarial.getSalarioLiquido() +
                     "<br>Total de descontos: " + calcSalarial.getTotalDescontos() +
                     "<br>Total de acrescimos: " + calcSalarial.getTotalAcrescimos() + 
                       "</html>");
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtValorHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorHoraActionPerformed
    
    
    //DECLARAÇÃO DO MÉTODO 
    
    public boolean verificarNumeros(){
    
    String valorHoraStr,horasTrabStr;
      
    //CAPTURA DOS VALORES
    
      valorHoraStr = txtValorHora.getText();
     
      horasTrabStr = txtHorasTrab.getText();
     
      //conversao de String para double 
      double valorHora,horasTrab;
     try{
      
      valorHora = Double.parseDouble(valorHoraStr);
      //horasTrab = Double.parseDouble(horasTrabStr);
      } catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Erro ao converter o valor por hora trabalhada!" + ex.getMessage());  
        txtValorHora.setText("");
       
        return false;
      }
     
     try{
      
      horasTrab = Double.parseDouble(horasTrabStr);
      //horasTrab = Double.parseDouble(horasTrabStr);
      } catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Erro ao converter o valor das horas trabalhadas!" + ex.getMessage());  
        txtHorasTrab.setText("");
      
        return false;
        
      }
        return true;
     
    }
    
    //DECLARAÇÃO DO MÉTODO 
    public boolean verificarVazio (){ 
    
      //VARIAVEL PARA GUARDAR VALOR DOS TEXT FIELDS
      
      String valorHoraStr,horasTrabStr;
      
    //CAPTURA DOS VALORES
      valorHoraStr = txtValorHora.getText();
      horasTrabStr = txtHorasTrab.getText();
      
      //VERIFICA SE OS CAMPOS ESTÃO COM ESPAÇOS
      if (valorHoraStr.trim().length() == 0){
          JOptionPane.showMessageDialog(null,"Forneça o valor por hora trabalhada !");
          txtValorHora.requestFocus();
          
          return false;
      
      }
      
      if (horasTrabStr.trim().length() == 0){
          JOptionPane.showMessageDialog(null,"Forneça o valor das horas trabalhadas !");
          txtHorasTrab.requestFocus();
      
          
          return false;
      
      }
          return true;
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCalc().setVisible(true);
            }
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbxConv;
    private javax.swing.JCheckBox cbxVA;
    private javax.swing.JCheckBox cbxVR;
    private javax.swing.JCheckBox cbxVT;
    private javax.swing.JComboBox<String> cmbDep;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblResp;
    private javax.swing.JRadioButton rbDepNao;
    private javax.swing.JRadioButton rbDepSim;
    private javax.swing.JTextField txtHorasTrab;
    private javax.swing.JTextField txtValorHora;
    // End of variables declaration//GEN-END:variables
}
